Add documentation for chain aliases flags
ava-labs/avalanche-docs pull request #1067
Opened 2022-11-15 17:42 UTC by aaronbuchwald

This PR adds documentation for the chain aliases flag, which should go in the next AvalancheGo release v1.9.3.

2022-11-15 18:23 UTC, yulin-dong requested changes

2022-11-15 18:23 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +The above example aliases the Blockchain whose ID is `"2K33xS9AyP9oCDiHYKVrHe7F54h2La5D8erpTChaAhdzeSu2RX"` to `"Swimmer"`. Chain aliases are added after adding primary network aliases and before any
Can you clarify `Chain aliases are added after adding primary network aliases and before any changes to the aliases via the admin API.`?

2022-11-17 20:59 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +The above example aliases the Blockchain whose ID is `"2K33xS9AyP9oCDiHYKVrHe7F54h2La5D8erpTChaAhdzeSu2RX"` to `"Swimmer"`. Chain aliases are added after adding primary network aliases and before any
@aaronbuchwald ^^

2022-11-17 21:09 UTC, StephenButtolph commented on docs/nodes/maintain/avalanchego-config-flags.md
> -fmt.Sprintf("If this node is not a validator, when a container is inserted into consensus, send a Push Query to %s validators and a Pull Query to the others. Must be <= k. Defaults to `0`.
oof

2022-11-17 21:50 UTC, StephenButtolph commented on docs/nodes/maintain/subnet-configs.md
> +The minimum delay enforce in building snowman++ blocks. Default is set to 1 second.
```suggestion
The minimum delay performed when building snowman++ blocks. Default is set to 1 second.
```

2022-11-17 21:50 UTC, StephenButtolph commented on docs/nodes/maintain/subnet-configs.md
> +As one of the ways to control network congestion, Snowman++ makes sure that no two blocks can be build before a `proposerMinBlockDelay` seconds delay. Some high-performance custom VM may find this to
```suggestion
As one of the ways to control network congestion, Snowman++ will only build a block `proposerMinBlockDelay` after the parent block's timestamp. Some high-performance custom VM may find this too strict. This flag allows tuning the frequency at which blocks are built.
```

2022-11-18 01:21 UTC, yulin-dong approved these changes

2022-11-18 01:23 UTC, merged