[WIP] Add style checker
ava-labs/avalanche-docs pull request #1093
Opened 2022-12-01 18:46 UTC by dasconnor

2022-12-04 20:08 UTC, yulin-dong requested changes
I was able to reproduce the lint error at https://github.com/ava-labs/avalanche-docs/actions/runs/3614628016/jobs/6091190197 locally with `textlint`. However, the question is that if we need to specify how to install and run `textlint` in `style-checker-notes.md` or remove it from CI as specified in `.github/workflows/linter.yml`. https://github.com/github/super-linter runs `textlint` plus `markdownlint`.
```
> npx textlint  --rule terminology docs/overview/getting-started/avalanche-consensus.md

/Users/yulindong/workspace/src/github.com/ava-labs/avalanche-docs/docs/overview/getting-started/avalanche-consensus.md
   78:104  ✓ error  Incorrect usage of the term: “Ava”, use “AVA” instead  terminology
  143:286  ✓ error  Incorrect usage of the term: “Ava”, use “AVA” instead  terminology
  153:103  ✓ error  Incorrect usage of the term: “Ava”, use “AVA” instead  terminology
  183:328  ✓ error  Incorrect usage of the term: “Ava”, use “AVA” instead  terminology

✖ 4 problems (4 errors, 0 warnings)
✓ 4 fixable problems.
Try to run: $ textlint --fix [file]
```

2022-12-05 16:32 UTC, yulin-dong commented on .github/styles/Vocab/Products/accept.txt
> +github
I think I got errors of github on pathes. However, as long as we can get errors cleared, I am fine with just GitHub.

2022-12-05 16:33 UTC, yulin-dong commented on docs/overview/getting-started/intro.md
> +<!-- markdownlint-disable MD013 -->
I got a lot of highlights on my VC editor without this line.

2022-12-05 17:04 UTC, dasconnor commented on docs/overview/getting-started/intro.md
> +<!-- markdownlint-disable MD013 -->
fixed

2022-12-05 17:13 UTC, yulin-dong commented on .github/workflows/linter.yml
> +          VALIDATE_NATURAL_LANGUAGE: false
Cool trick!

2022-12-05 19:07 UTC, yulin-dong approved these changes

2022-12-05 19:07 UTC, merged