Updating doc adding PublicNode
ava-labs/avalanche-docs pull request #1161
Opened 2023-01-17 15:18 UTC by wycks

Adding PublicNode to Community Providers for C-Chain RPC.

2023-01-17 15:31 UTC, yulin-dong requested changes

2023-01-17 15:31 UTC, yulin-dong commented on docs/apis/avalanchego/public-api-server.md
> +- Optimized for Speed and reliability - Check our page for stats
Please update to proper letter cases.
```suggestion
- Optimized for speed and reliability - check our page for stats
```

2023-01-17 15:31 UTC, yulin-dong commented on docs/apis/avalanchego/public-api-server.md
> +[PublicNode](https://avalanche.publicnode.com) supports C-Chain
```suggestion
[PublicNode](https://avalanche.publicnode.com) supports the C-Chain on the Mainnet.
```

2023-01-18 01:12 UTC, wycks commented on docs/apis/avalanchego/public-api-server.md
> +- Globally distributed infrastructure (our own bare metal)
Yes Allnodes runs it own datacenter for avalanche validators. PublicNode is a free service  run by Allnodes.

2023-01-18 14:39 UTC, yulin-dong commented on docs/apis/avalanchego/public-api-server.md
> +- Globally distributed infrastructure (our own bare metal)
`Run by` or `run on` AllNodes? Are you part of AllNodes?

2023-01-18 16:44 UTC, wycks commented on docs/apis/avalanchego/public-api-server.md
> +- Globally distributed infrastructure (our own bare metal)
Run by Allnodes on Allnodes Validators, yes I work for Allnodes. But this is a free service and not part of our business or main website.

2023-01-18 16:52 UTC, yulin-dong commented on docs/apis/avalanchego/public-api-server.md
> +- Globally distributed infrastructure (our own bare metal)
I would suggest you change it to "Globally distributed infrastructure on Allnodes"

2023-01-18 16:55 UTC, wycks commented on docs/apis/avalanchego/public-api-server.md
> +- Globally distributed infrastructure (our own bare metal)
Will do thank your for your guidance

2023-01-21 10:23 UTC, cgcardona commented
Closing in favor of https://github.com/ava-labs/avalanche-docs/pull/1170. Thanks!

2023-01-21 10:23 UTC, closed without merging