Update set-up-node-with-installer.md
ava-labs/avalanche-docs pull request #1163
Opened 2023-01-19 02:48 UTC by dubrado

Just some small edits to the language and format in some areas to clean things up for the newer node builders with less experience.

2023-01-19 05:28 UTC, yulin-dong requested changes

2023-01-19 05:28 UTC, yulin-dong commented on docs/nodes/build/set-up-node-with-installer.md
> +NOTE: HW requirements shall scale with the amount of AVAX staked on
Should docusaurus admonition https://docusaurus.io/docs/markdown-features/admonitions be used here?

2023-01-19 15:38 UTC, yulin-dong requested changes

2023-01-19 15:38 UTC, yulin-dong commented on docs/nodes/build/set-up-node-with-installer.md
> +NOTE: If you choose to allow RPC requests on any network interface you will need
admonition

2023-01-21 09:39 UTC, cgcardona commented
Please merge the latest from `master` into your PR.

2023-01-21 09:48 UTC, cgcardona submitted a review, later dismissed
LGTM once you merge `master` into your branch and after the requested admonitions are in place.

2023-01-23 15:42 UTC, yulin-dong requested changes

2023-01-23 15:42 UTC, yulin-dong commented on docs/nodes/build/set-up-node-with-installer.md
> +NOTE: HW requirements shall scale with the amount of AVAX staked on
```suggestion
::: note
 HW requirements shall scale with the amount of AVAX staked on
```

add the closing :::

2023-01-23 15:52 UTC, yulin-dong approved these changes

2023-01-23 15:52 UTC, merged