Clarify the format and content of the `blockTimestamp` value
ava-labs/avalanche-docs pull request #1175
Opened 2023-01-23 23:25 UTC by holisticode

This PR:
* adds a "warning" area explaining that the `blockTimestamp` entry must be valid
* replaces all occurrences of `"blockTimestamp": 0` to a valid value `1684883935` (corresponds to `Tuesday, May 23, 2023 6:18:55 PM GMT-05:00`)

2023-01-23 23:26 UTC, yulin-dong approved these changes

2023-01-23 23:27 UTC, yulin-dong requested changes

2023-01-23 23:27 UTC, yulin-dong commented on docs/subnets/customize-a-subnet.md
> +to a valid UNIX timestamp value which is in the _future_ relative to the _head of the chain_.
```suggestion
to a valid Unix timestamp value which is in the _future_ relative to the _head of the chain_.
```

2023-01-23 23:34 UTC, holisticode commented on docs/subnets/customize-a-subnet.md
> +to a valid UNIX timestamp value which is in the _future_ relative to the _head of the chain_.
Fixed

2023-01-24 21:03 UTC, cgcardona approved these changes
LGTM

2023-01-24 21:16 UTC, aaronbuchwald approved these changes

2023-01-24 21:16 UTC, yulin-dong approved these changes

2023-01-24 21:16 UTC, merged