Update PrecompileGen tutorial to use create precompile script
ava-labs/avalanche-docs pull request #1196
Opened 2023-02-05 03:48 UTC by aaronbuchwald

This PR updates the PrecompileGen tutorial to use the new script `./scripts/create_precompile.sh` instead of directly running it with the `go run ...` command.

This change was made to address https://github.com/ava-labs/subnet-evm/issues/483.

Since we use the blst library in AvalancheGo, we need to set a CGO flag when compiling/running subnet-evm on some OSs. I have not been able to reproduce this bug, so we should hold off on merging this PR until the reporter confirms that this resolves the issue and the corresponding subnet-evm PR gets merged.

2023-02-06 15:03 UTC, ceyonur requested changes
I commented in the feature-PR

https://github.com/ava-labs/subnet-evm/pull/489#issuecomment-1419227290

2023-02-06 17:37 UTC, darioush approved these changes

2023-02-06 19:41 UTC, anusha-ctrl approved these changes

2023-02-06 23:42 UTC, yulin-dong approved these changes

2023-02-06 23:42 UTC, merged

2023-02-07 13:33 UTC, ceyonur commented
Hmm I think we should have waited until we have a release for subnet-evm? What do you say? @aaronbuchwald