Add page - Create a simple vm from scratch
ava-labs/avalanche-docs pull request #1267
Opened 2023-03-21 08:03 UTC by boulix3

Related to #1266

2023-03-29 00:42 UTC, cgcardona requested changes
Thanks!

2023-03-29 00:42 UTC, cgcardona commented on docs/subnets/create-a-simple-vm-from-scratch.md
> +  MESSAGE_BUILD_BLOCK value.
Add backticks around `MESSAGE_BUILD_BLOCK`

2023-03-29 07:59 UTC, boulix3 commented on docs/subnets/create-a-simple-vm-from-scratch.md
> +  - Param : a
The rest of the text is on the next line because of the line length restriction.

2023-04-06 10:34 UTC, boulix3 commented
Hello @cgcardona, @yulin-dong, I have a new page to add, but it's quite big and I don't know if I should add it to this PR.
[Create vm from scratch using c#](https://github.com/boulix3/avalanche-docs/blob/csharp-vm/docs/subnets/create-a-simple-vm-from-scratch-csharp.md)
Here is a [preview of the page](https://boulixavalanchedocs.web.app/subnets/create-a-simple-vm-from-scratch-csharp) hosted on firebase.
What should I do?
- Add it to this PR
- Wait for this PR to be completed and create a new one
- Create a parallel PR (but containing changes relating to this one as well)

2023-04-07 14:19 UTC, yulin-dong commented
> Hello @cgcardona, @yulin-dong, I have a new page to add, but it's quite big and I don't know if I should add it to this PR. [Create vm from scratch using c#](https://github.com/boulix3/avalanche-docs/blob/csharp-vm/docs/subnets/create-a-simple-vm-from-scratch-csharp.md) Here is a [preview of the page](https://boulixavalanchedocs.web.app/subnets/create-a-simple-vm-from-scratch-csharp) hosted on firebase. What should I do?
> 
> * Add it to this PR
> * Wait for this PR to be completed and create a new one
> * Create a parallel PR (but containing changes relating to this one as well)

Please create a separate PR. Thanks.

2023-04-07 14:35 UTC, boulix3 reviewed
Applied all requested changes

2023-04-19 19:30 UTC, cgcardona commented
Closing in favor of https://github.com/ava-labs/avalanche-docs/pull/1310

2023-04-19 19:30 UTC, closed without merging