sync avalanchego flags
ava-labs/avalanche-docs pull request #1289
Opened 2023-03-30 15:31 UTC by ceyonur

Syncs the page with latest avalanchego flags.

2023-03-30 16:08 UTC, ceyonur commented on docs/nodes/maintain/avalanchego-config-flags.md
> +#### Snow Parameters
yep moved under to Consensus Paramaters

2023-03-30 16:19 UTC, yulin-dong requested changes

2023-03-30 16:19 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +#### network-health-max-outstanding-request-duration` (duration)
-- for consistency?

2023-03-30 16:19 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +##### `throttler-inbound-cpu-max-recheck-delay` (duration)
-- for consistency?

2023-03-30 16:19 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +##### `snow-max-time-processing` (duration)
-- for consistency?

2023-03-30 16:19 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +##### `snow-mixed-query-num-push-vdr` (uint)
-- for consistency?

2023-03-30 16:19 UTC, yulin-dong commented on docs/nodes/maintain/avalanchego-config-flags.md
> +##### `snow-mixed-query-num-push-non-vdr` (uint)
-- for consistency?

2023-03-31 17:14 UTC, ceyonur commented on docs/nodes/maintain/avalanchego-config-flags.md
> +##### `snow-optimal-processing` (int)
good catches, updated them

2023-03-31 17:19 UTC, yulin-dong approved these changes

2023-03-31 17:19 UTC, merged