Cross subnet communication
ava-labs/avalanche-docs pull request #1313
Opened 2023-04-19 21:53 UTC by martineckardt

2023-04-19 22:09 UTC, laviniat1996 commented
@martineckardt can you please fix the failing checks?

2023-04-19 23:32 UTC, laviniat1996 requested changes

2023-04-19 23:32 UTC, laviniat1996 commented on docs/subnets/cross-subnet-communication.md
> +![image showing four steps of cross-Subnet communication: Signing, aggregation, Delivery and Verification](/img/cross-Subnet-communication.png)
The image name is wrong because of the capital letter. The name should be cross-subnet-communication.png

2023-04-19 23:32 UTC, laviniat1996 commented on docs/subnets/cross-subnet-communication.md
> +
Please add the word "Sharding" to `.github/styles/Vocab/Products/accept.txt`

2023-04-23 16:43 UTC, laviniat1996 commented
```
/github/workspace/docs/subnets/cross-subnet-communication.md:5:101 MD013/line-length Line length [Expected: 100; Actual: 124]
/github/workspace/docs/subnets/cross-subnet-communication.md:52:101 MD013/line-length Line length [Expected: 100; Actual: 216]
/github/workspace/docs/subnets/cross-subnet-communication.md:57:101 MD013/line-length Line length [Expected: 100; Actual: 101]
```

Can you please fix this linting errors?

2023-04-23 18:05 UTC, dubrado submitted a review, later dismissed

2023-04-23 22:08 UTC, laviniat1996 approved these changes

2023-04-24 20:41 UTC, laviniat1996 commented
@martineckardt a knit pick, but could you please remove the numbering as it is not necessary, and doesn't fit with the rest of our docs? thank you

2023-04-24 21:29 UTC, StephenButtolph commented on docs/subnets/cross-subnet-communication.md
> +validators of two Subnets. The content of the messages can contain arbitrary payloads.
```
any-to-any communication between the validators of two Subnets
```
This reads to be like any validator in Subnet A can send a message to any validator in Subnet B.

This really isn't the point of Warp (sending messages between validators like this is trivial)... Warp is intended to enable any Subnet A to be able to send a message to any other Subnet B. Generally Subnet A (as an entity) sending a message to Subnet B (as an entity). This means that every validator in Subnet B should receive this message.

```suggestion
Avalanche Warp Messaging (AWM) enables native cross-Subnet communication and allows [Virtual Machine
(VM)](./README.md#virtual-machines) developers to implement arbitrary communication protocols between any two Subnets.
```

2023-04-24 21:29 UTC, StephenButtolph commented on docs/subnets/cross-subnet-communication.md
> +Subnets. The messages do not pass through a central protocol or trusted entity, and there is no
```
Messages are delivered directly from the validators of one Subnet to the validators of the other
Subnets
```
This seems to contradict the below statement:
```
It is up to the Subnets and their users to determine how they want to transport data from the
validators of the origin Subnet to the validators of the destination Subnet and what guarantees they
want to provide for the transport.
```
I think that the first sentence is a bit confusing / misleading. The second paragraph is exactly correct.

2023-04-25 19:34 UTC, dubrado approved these changes

2023-04-25 19:41 UTC, merged