Docs: added page for running a node with latitude
ava-labs/avalanche-docs pull request #1320
Opened 2023-04-25 04:39 UTC by meaghanfitzgerald

Added a page for running a node with [Latitude.sh](https://github.com/NottherealIllest/Latitude.sh-post/blob/main/avalanhe/avax-copy.md) to the build menu where the node tutorials currently exist

2023-04-25 04:48 UTC, meaghanfitzgerald commented
I currently am not able to use markdownlint to clean up my files, even though I have:

1.installed markdownlint on vscode and set it as my default formatter, then called `Opt+Shift+F`
2.`Opt+shift+P` and chosen "Format Document"
3. Hovered over the error, selected "Quick Fix", then "Fix all supported markdownlint violations in this document"
4. installed the CLI, set my config file to this repo's `.markdownlint.json` and invoked it there

see video for demo of markdown doing nothing: 
https://user-images.githubusercontent.com/99047250/234176788-e23e5b9b-ac77-4661-832c-5ac56db6b28d.mov

2023-04-25 14:19 UTC, yulin-dong requested changes

2023-04-25 14:19 UTC, yulin-dong commented on docs/nodes/build/set-up-an-avalanche-node-with-latitude.md
> +<<<<<<< HEAD
There are quite a few left-over by git merge which should be cleaned up.

2023-04-25 14:59 UTC, yulin-dong commented on docs/nodes/build/set-up-an-avalanche-node-with-latitude.md
> +```json
Please format this json text.

2023-04-25 14:59 UTC, yulin-dong commented on docs/nodes/build/set-up-an-avalanche-node-with-latitude.md
> +`{"jsonrpc":"2.0","result":{"nodeID":"KhDnAoZDW8iRJ3F26iQgK5xXVFMPcaYeu"},"id":1}`
json format

2023-04-25 15:00 UTC, yulin-dong commented on docs/nodes/build/set-up-an-avalanche-node-with-latitude.md
> +curl -X POST --data '{
json format

2023-04-25 15:19 UTC, yulin-dong commented
LGTM for the format. Please get an approval for the content.

2023-04-26 18:50 UTC, dubrado approved these changes

2023-04-26 18:53 UTC, amandamarquis1 approved these changes
Approving changes

2023-04-26 18:55 UTC, dubrado approved these changes

2023-04-26 18:57 UTC, dubrado approved these changes

2023-04-26 18:57 UTC, dubrado approved these changes

2023-04-26 19:00 UTC, yulin-dong approved these changes

2023-04-26 19:00 UTC, merged