Add fee schedule for Fuji
ava-labs/avalanche-docs pull request #1680
Opened 2024-02-19 09:58 UTC by laviniat1996

2024-02-19 15:02 UTC, yulin-dong requested changes
I would suggest to list out Fuji differences using the same format as that in https://docs.avax.network/nodes/validate/how-to-stake#fuji-testnet.

2024-02-26 14:52 UTC, dubrado approved these changes

2024-02-26 17:13 UTC, laviniat1996 commented on docs/reference/standards/guides/txn-fees.md
> +- Create Blockchain: 0.1 AVAX
@yulin-dong not sure what's wrong with that info?

2024-02-26 17:16 UTC, laviniat1996 commented on docs/reference/standards/guides/txn-fees.md
> +- Create Blockchain: 0.1 AVAX
@yulin-dong fixed b521798d621e6928a32a42d08d52619db9ce5d87

2024-02-26 20:00 UTC, yulin-dong commented on docs/reference/standards/guides/txn-fees.md
> +- Create Blockchain: 0.1 AVAX
@laviniat1996 please fix build

2024-02-27 12:01 UTC, laviniat1996 commented on docs/reference/standards/guides/txn-fees.md
> +- Create Blockchain: 0.1 AVAX
@yulin-dong done

2024-02-27 14:19 UTC, yulin-dong approved these changes

2024-02-29 22:45 UTC, merged