Update snowtrace.mdx
ava-labs/avalanche-docs pull request #1889
Opened 2024-09-17 12:38 UTC by Migl992

- update team name
- adding missing features

2024-09-19 20:59 UTC, owenwahlgren requested changes

2024-09-19 20:59 UTC, owenwahlgren commented on content/integrations/snowtrace.mdx
> +6. **Export data**: Exporta data in bulks visiting the [dumps page](https://snowtrace.io/dumps) or the [export data page](https://snowtrace.io/exportdata)
Misspelling: "Exporta"

2024-09-19 20:59 UTC, owenwahlgren commented on content/integrations/snowtrace.mdx
> +available: ["C-Chain", "DFK", "Dexalot", "UPTN", "Lamina1", "Shrapnel", "XANA-CHAIN", "Playdapp", "Meld", "Beam", "PLAYA3ULL Games", "DOS", "Numbers", "StraitsX"]
For now lets just put
```
available: ["C-Chain", "All EVM L1s"]
```

2024-09-23 06:47 UTC, Migl992 commented on content/integrations/snowtrace.mdx
> +available: ["C-Chain", "DFK", "Dexalot", "UPTN", "Lamina1", "Shrapnel", "XANA-CHAIN", "Playdapp", "Meld", "Beam", "PLAYA3ULL Games", "DOS", "Numbers", "StraitsX"]
we can use: Avalanche EVM L1s

2025-01-13 16:06 UTC, closed without merging