Add how-to-mint-erc721-using-openzeppelin
ava-labs/avalanche-docs pull request #278
Opened 2021-09-01 06:03 UTC by therealharpaljadeja

2021-09-03 22:12 UTC, jpop32 commented
Please add the images used into the PR and link them relative to root of tutorial (currently they are linked out to your repo). Also, please rename the image files so they have a common and unique prefix that can identify them as belonging to this tutorial (GitBook tool we use puts all the images in a single direcory). For example
minting-erc721-00-name-if-first-image.png, 
minting-erc721-01-name-if-second-image.png,
...

2021-09-03 22:14 UTC, jpop32 commented
Please add a conclusion / summary part to round out the tutorial. The ending is kinda abrupt.

2021-09-03 22:15 UTC, jpop32 commented
Please remove the numbering of the steps and format the instructions so they flow naturally: use sentences and paragraphs instead of a list of steps.

2021-09-04 15:24 UTC, therealharpaljadeja commented
Hi @jpop32, I have made the changes as requested please have a look and let me know if there are any more. Thanks 🙂

2021-09-06 14:40 UTC, jpop32 commented
Thanks, that's great. Unfortunately, you cannot manually add files into the .gitbook directory, that causes problems with syncing. Can you just place the images in the /images directory in your tutorial directory? Apologies, I could have been more clear.

2021-09-06 15:53 UTC, therealharpaljadeja commented
Thanks, @jpop32  for the review I have moved the images from .gitbook to images directory in my tutorial directory. Let me know if there are any more changes thanks 🙂.

2021-09-13 13:42 UTC, cgcardona requested changes
Minor changes requested

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +### This tutorial teaches you to deploy your own ERC721 token on Avalanche FUJI C-chain testnet.
[Heading levels should only increment by one level at a time](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md001)

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +## Contents
[Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md022)

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +- [Getting images ready to be uploaded to decentralized storage.](#getting-images-ready-to-be-uploaded-to-decentralized-storage) (IPFS in this tutorial)
Replace `-` w/ `*` for list items to match the rest of the docs

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +### <u>Getting images ready to be uploaded to decentralized storage.</u>
Underlined text is reserved for links. Remove `<u>` tag

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +<br>
Remove `<br>` tag

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +
Only have 1 blank line at the end of the file.

2021-09-13 13:42 UTC, cgcardona commented on build/tutorials/tutorials-contest/how-to-mint-erc721-using-openzeppelin/tutorial.md
> +
Only have 1 blank line between paragraphs.

2021-09-13 17:12 UTC, therealharpaljadeja commented
Thanks, @cgcardona for the constructive feedback. I have made the changes please have a look and let me know if any more changes 😅

2021-10-01 12:50 UTC, merged