Avalanche tutorial contest - Distributed file manager
ava-labs/avalanche-docs pull request #282
Opened 2021-09-01 11:24 UTC by rajranjan0608

This is the submission PR (Distributed File Manager) for Round 2 of Avalanche's tutorial contest.

2021-09-03 23:04 UTC, jpop32 commented on build/tutorials/tutorials-contest/distributed-file-manager/README.md
> +```markup
`html` type will render better.

2021-09-03 23:05 UTC, jpop32 commented on build/tutorials/tutorials-contest/distributed-file-manager/README.md
> +```javascript
`solidity` instead of `javascript`. Check other code blocks too, please.

2021-09-03 23:08 UTC, jpop32 commented
Please rename the image files so they have a common and unique prefix that can identify them as belonging to this tutorial (GitBook tool we use puts all the images in a single direcory). For example
file-manager-00-name-of-first-image.png,
file-manager-01-name-of-second-image.png,
...

2021-09-05 12:04 UTC, rajranjan0608 commented
@jpop32 Made required changes. Please have a look. Thanks.

2021-09-13 13:34 UTC, cgcardona requested changes
Minor changes requested

2021-09-13 13:34 UTC, cgcardona commented on build/tutorials/tutorials-contest/distributed-file-manager/frontend/App.js
> +
Port js -> ts

2021-09-13 13:34 UTC, cgcardona commented on build/tutorials/tutorials-contest/distributed-file-manager/README.md
> +- Basic familarity with [Git](https://git-scm.com/), [NodeJS](https://nodejs.org/en) and [npm](https://www.npmjs.com/).
Replace `-` w/ `*` for list items to match the rest of the docs.

2021-09-13 13:34 UTC, cgcardona commented on build/tutorials/tutorials-contest/distributed-file-manager/README.md
> +```javascript
Use `typescript` instead of `javascript`

2021-09-13 20:00 UTC, rajranjan0608 commented on build/tutorials/tutorials-contest/distributed-file-manager/frontend/App.js
> +
Issue with porting mentioned [here](https://github.com/ava-labs/avalanche-docs/pull/284#discussion_r707637856)

2021-10-01 12:47 UTC, merged