Avalanche tutorial contest (Round 2) - Avalanche e-voting DApp
ava-labs/avalanche-docs pull request #283
Opened 2021-09-01 11:44 UTC by rajranjan0608

This is the submission PR (Avalanche e-voting DApp) for Round 2 of Avalanche's tutorial contest.

2021-09-03 22:58 UTC, jpop32 commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/README.md
> +```javascript
could you please add the correct format type? So `solidity` instead of `javascript`. Please check other code blocks too.

2021-09-03 23:01 UTC, jpop32 commented
Comments from other reviews are also valid: please rename the images to have an identifiable prefix. Extract large (more than 20-ish lines) to a separate file, link to it and just highlight the most important parts.

2021-09-05 12:05 UTC, rajranjan0608 commented
@jpop32 Made required changes. Please have a look. Thanks.

2021-09-13 13:32 UTC, cgcardona requested changes
Minor changes requested

2021-09-13 13:32 UTC, cgcardona commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/frontend/ActiveElections.js
> +import React, { Component } from "react";
Port js -> ts

2021-09-13 13:32 UTC, cgcardona commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/frontend/ActiveElections.js
> +var Election = (props) => (
Replace `var` keyword w/ `let`

2021-09-13 13:32 UTC, cgcardona commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/frontend/ActiveElections.js
> +  loadData = async () => {
After porting to typescript add return type for each function.

2021-09-13 13:32 UTC, cgcardona commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/README.md
> +## Introduction
[Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md022)

2021-09-13 13:32 UTC, cgcardona commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/README.md
> +- Basic familarity with [NodeJS](https://nodejs.org/en) and [npm](https://www.npmjs.com/).
Replace `-` w/ `*` for list items to match the rest of the docs

2021-09-13 13:32 UTC, cgcardona commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/README.md
> +```javascript
Use `typescript` instead of `javascript`

2021-09-13 19:58 UTC, rajranjan0608 commented on build/tutorials/tutorials-contest/evoting-avalanche-dapp/frontend/ActiveElections.js
> +import React, { Component } from "react";
Issue with porting mentioned [here](https://github.com/ava-labs/avalanche-docs/pull/284#discussion_r707637856).

2021-10-01 12:47 UTC, merged