"sig-verify-tutorial" for Round 2
ava-labs/avalanche-docs pull request #286
Opened 2021-09-01 13:21 UTC by aratrika1996

This pull request is for red·dev's entry "sig-verify-tutorial" for Round 2 of the Avalanche Tutorials contest. This entry was submitted originally under the name of red·dev's CEO, Christopher David Sturgeon ("Kit"). It is a group effort by part of the red·dev team. Today, team member Aratrika Mukherjee is submitting the request. We look forward to your critique and comments! Thank you.

2021-09-03 19:51 UTC, cgcardona requested changes
Why are there 5,000 files changed in this diff? Can you confirm that you have the latest from `master` merged into this PR before I review it? Thanks

2021-09-03 22:00 UTC, jpop32 commented
Apparently, you included the whole project with the tutorial. There's no need for that, you can only include the source files. My guess is (not a js dev myself) that for example the whole node_modules directory can be omitted and recreated locally when someone pulls the project.

2021-09-04 10:54 UTC, aratrika1996 commented
I have made the required changes and removed all the unnecessary files including the node modules. Kindly review the PR. If you need to review any of the files that I removed, the original repo is here: https://github.com/red-dev-inc/sig-verify-tutorial

2021-09-06 00:25 UTC, kitpub commented
Hello, we're ready to make any requested changes. Aratrika is working on IST and I'm on EDT just fyi. We overlap each morning between 8 AM and 10:30 AM EDT.

2021-09-06 14:05 UTC, aratrika1996 commented
Renamed png for standards compliance per jpop32's comment on our other tutorial's pull request.

2021-09-07 13:19 UTC, kitpub commented
Hello! Are revisions due today? If so, we think we've made the ones needed, but please confirm. If you would like to request more changes, we would be happy to make additional edits, but we will need a day or two more to complete them due to time zone differences, etc. Thanks. We've really enjoyed creating material for this contest.

2021-09-13 13:16 UTC, cgcardona requested changes
Great work. Minor changes requested.

2021-09-13 13:16 UTC, cgcardona commented on build/tutorials/tutorials-contest/red-dev-sig-verify-tutorial/README.md
> +# Tutorial: Avalanche Signature Verification in a dApp
* [Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md022)
* [Multiple top-level headings in the same document](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md025)

2021-09-13 13:16 UTC, cgcardona commented on build/tutorials/tutorials-contest/red-dev-sig-verify-tutorial/README.md
> +```javascript
Please port from javascript -> typescript

2021-09-13 13:16 UTC, cgcardona commented on build/tutorials/tutorials-contest/red-dev-sig-verify-tutorial/README.md
> +```
What is the data type of this code?

2021-09-13 13:16 UTC, cgcardona commented on build/tutorials/tutorials-contest/red-dev-sig-verify-tutorial/README.md
> +    let mBuf = Buffer.from(message, 'utf8')
Add type to each variable declaration after porting to typescript.

2021-09-13 13:16 UTC, cgcardona commented on build/tutorials/tutorials-contest/red-dev-sig-verify-tutorial/README.md
> +```
Data type of code block?

2021-09-13 13:16 UTC, cgcardona commented on build/tutorials/tutorials-contest/red-dev-sig-verify-tutorial/README.md
> +```
Data type of this block of code?

2021-09-14 13:26 UTC, aratrika1996 commented
I have made all the required changes to the best of my understanding. Please review the PR and kindly let us know if any more revisions are required.

2021-09-14 18:01 UTC, kitpub commented
We are so honored to have won and to have had this chance to contribute to Avalanche! Thank you so much for the opportunity. The team at red·dev is looking forward to much more to come as the ecosystem grows, and we are 100% committed to its success. Please let us know how we can help going forward.

2021-09-14 18:22 UTC, kitpub commented
One follow-up question. Regarding the signature verification process we describe in this tutorial, we believe it is correct. However, we are not cryptographers. We are just software devs who have some experience with applied cryptography and love building on Avalanche. I'm wondering what level of auditing for correctness our tutorial received? Since a defect in it could allow an attacker to drain large amounts of AVAX from our dapp, it's a concern, especially now since others might follow this tutorial and use the same technique for their dapps.

On a related note, we also did a pull request for the ECDSA repo we used (and modified slightly). https://github.com/tdrerup/elliptic-curve-solidity/pull/3 As you can see, they have not had time to look at it yet and appear to be busy with other things.

2021-10-01 12:46 UTC, merged