feat: add avalanche DAO tutorial files
ava-labs/avalanche-docs pull request #293
Opened 2021-09-01 21:29 UTC by ArturVargas

2021-09-03 20:01 UTC, cgcardona requested changes
Nice work. I requested some changes which are mostly related to formatting. Thanks

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```
Have this code block be of type `solidity`

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```
Have all code blocks which contain solidity code be of type `solidity`

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```
Have all code blocks which contain solidity code be of type `solidity`

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```
Have all code blocks which contain solidity code be of type `solidity`

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```moonscript
Have all code blocks which contain solidity code be of type `solidity`

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```moonscript
Have all code blocks which contain solidity code be of type `solidity`

2021-09-03 20:01 UTC, cgcardona commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +```moonscript
Have all code blocks which contain solidity code be of type `solidity`

2021-09-03 22:47 UTC, ArturVargas commented on build/tutorials/tutorials-contest/avalanche-DAO/README.md
> +`` The first line tells you that the source code is licensed under the GPL version 3.0. Machine-readable license specifiers are important in a setting where publishing the source code is the default.
just to highlight

2021-09-06 15:13 UTC, jpop32 commented
The point of image file renaming is to group all the images belonging to a single tutorial together. Gitbook (the tool we use to display docs) will move all the files into a single directory. So in order for them to be grouped they need all to have a single, identifiable prefix. So, please make all of the image filenames start with `avalanche-dao-`.

2021-10-01 12:43 UTC, merged