Avalanche Stats
ava-labs/avalanche-docs pull request #312
Opened 2021-09-13 07:26 UTC by 0fatih

I saw on twitter that avalanche has a stats website. I think we should include this in the docs.

2021-09-13 13:00 UTC, cgcardona requested changes
Thanks. Requested changes.

2021-09-13 13:00 UTC, cgcardona commented on build/tutorials/nodes-and-staking/README.md
> +| **​**[**Avalanche Stats**](https://docs.avax.network/build/tutorials/nodes-and-staking/upgrade-your-avalanchego-node)**​** | Avalanche Stats. |
Also add the link to `SUMMARY.md`

2021-09-13 14:29 UTC, 0fatih commented
I made the changes you requested. Please let me know if I have another mistake

2021-09-14 15:04 UTC, yulin-dong requested changes

2021-09-14 15:04 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +Shows how much gas is burned in the last day.
```suggestion
Shows how much gas is burned in every day.
```

2021-09-14 15:04 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +Shows how much gas is used in the last day.
```suggestion
Shows how much gas is used in every day.
```

2021-09-14 15:04 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +Shows how many transaction were made in the last day.
```suggestion
Shows how many transaction were made in every day.
```

2021-09-14 15:45 UTC, 0fatih commented
@yulin-dong thanks!

2021-09-14 17:50 UTC, yulin-dong requested changes

2021-09-14 17:50 UTC, yulin-dong commented on build/tools/README.md
> +[**Avalanche Stats**](avalanche-stats.md): You can learn the status of Avalanche and nodes.
```suggestion
[**Avalanche Stats**](avalanche-stats.md): Dashboard for Avalanche stats.
```

2021-09-14 17:50 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +We created a [stats][https://stats.avax.network/] website that you can learn a lot of things about avalanche's current status.
```suggestion
We have created a [stats][https://stats.avax.network/] website from where you can learn a lot about avalanche's current stats.
```

2021-09-14 17:50 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +## What is in there
```suggestion
## What are included?
```

2021-09-14 17:50 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +We have 3 main concepts in our stats: Staking, Validator Health Check and C-Chain Activity.
```suggestion
We have 3 main areas in our stats: Staking, Validator Health Check and C-Chain Activity.
```

2021-09-14 17:50 UTC, yulin-dong commented on build/tools/avalanche-stats.md
> +You can access this part from [this][https://stats.avax.network/dashboard/staking/] link. And you can see:
```suggestion
You can access this part from [this][https://stats.avax.network/dashboard/staking/] link from which you will get following info:
```

2021-09-14 18:40 UTC, cgcardona approved these changes
Thanks 🎩

2021-09-14 18:41 UTC, merged