Verify smart contracts with truffle verify
ava-labs/avalanche-docs pull request #403
Opened 2021-11-22 21:08 UTC by Julian-dev28

Update for users to verify smart contracts with truffle verify on Avalanche

2021-11-22 23:38 UTC, yulin-dong requested changes

2021-11-22 23:38 UTC, yulin-dong commented on build/tutorials/smart-contracts/verify-smart-contracts-with-truffle-verify.md
> +# Verify Smart Contracts with truffle verify
Is this the same title as the top one?

2021-11-22 23:40 UTC, yulin-dong commented
Anything we need to do with https://docs.avax.network/build/tutorials/smart-contracts/verify-smart-contracts-with-sourcify-truffle? Is https://docs.avax.network/build/tutorials/smart-contracts/verify-smart-contracts-with-sourcify-truffle still up-to-date and applicable?

2021-11-22 23:47 UTC, yulin-dong requested changes

2021-11-22 23:47 UTC, yulin-dong commented on build/tutorials/smart-contracts/verify-smart-contracts-with-truffle-verify.md
> +## Create a project
I re-organized the heading, please verify they are correct.

2021-11-22 23:47 UTC, yulin-dong commented on build/tutorials/smart-contracts/verify-smart-contracts-with-truffle-verify.md
> +## Verify Smart Contracts with truffle verify
Is this heading the same as the top one on line 1?

2021-11-24 20:24 UTC, Julian-dev28 reviewed
Good to go

2021-12-02 03:26 UTC, yulin-dong approved these changes

2021-12-02 03:27 UTC, merged