Update C-Chain config docs
ava-labs/avalanche-docs pull request #428
Opened 2021-12-03 05:27 UTC by aaronbuchwald

This PR updates the C-Chain config docs to reflect the latest configuration options.

2021-12-03 06:09 UTC, dhrubabasu requested changes
Left a few nits

2021-12-03 06:09 UTC, dhrubabasu commented on docs/build/references/command-line-interface.md
> +   "snowman-api-enabled":false,
nit: let's keep it to an indent-size of two spaces and add a space between the key and value

2021-12-03 06:09 UTC, dhrubabasu commented on docs/build/references/command-line-interface.md
>  Global transaction fee \(price \* gaslimit\) cap \(measured in AVAX\) for send-transction variants. Defaults to 100.
```suggestion
Global transaction fee \(price \* gaslimit\) cap \(measured in AVAX\) for send-transaction variants. Defaults to 100.
```

2021-12-03 06:09 UTC, dhrubabasu commented on docs/build/references/command-line-interface.md
> +If true, the APIs will allow transactions that are not replay protected to be issued through this node. Defaults to false.
```suggestion
If true, the APIs will allow transactions that are not replay protected (EIP-155) to be issued through this node. Defaults to false.
```

2021-12-03 06:09 UTC, dhrubabasu commented on docs/build/references/command-line-interface.md
> +**Databaset**
```suggestion
**Database**
```

2021-12-03 06:25 UTC, dhrubabasu approved these changes

2021-12-10 23:33 UTC, yulin-dong approved these changes

2021-12-10 23:33 UTC, merged