Main dashboard: Correct balloon help text
ava-labs/avalanche-docs pull request #524
Opened 2022-01-18 15:53 UTC by neuhaus

The panel shows the percentages, not the numbers

2022-01-18 16:07 UTC, neuhaus commented
I've also fixed two broken links, a typo and improved the wording.

2022-01-20 15:01 UTC, yulin-dong requested changes

2022-01-20 15:01 UTC, yulin-dong commented on dashboards/main.json
> +              "url": "/d/DHT8r2znz/machine-metrics?orgId=1&refresh=10s"
This should not be changed. Are you running it locally?

2022-01-20 17:02 UTC, yulin-dong approved these changes

2022-01-20 17:02 UTC, merged