tutorials: Promote AvalancheGo installer as first/default method
ava-labs/avalanche-docs pull request #667
Opened 2022-04-02 18:14 UTC by moreati

I believe it's just an accident of history that the manual instructions were at the top of the list. The installer script is easier, and more reliable.

2022-04-02 23:01 UTC, gatesyp commented
Weighing in here -- I like having manual instructions at the top just because I was looking to dev on Avalanche-Go. But if the main audience of the docs are people who want to just get their node up and running, then I think this is a great improvement

2022-04-03 22:15 UTC, yulin-dong commented
> Weighing in here -- I liked having manual instructions at the top just because I was looking to dev on Avalanche-Go. But if the main audience of the docs are people who want to just get their node up and running, then I think this is a great improvement

I agree with you and will close this PR and leave it as is.

2022-04-03 22:15 UTC, closed without merging

2022-04-04 13:28 UTC, yulin-dong requested changes

2022-04-04 13:28 UTC, yulin-dong commented on docs/build/tutorials/nodes-and-staking/set-up-node-with-installer.md
> +# Run an Avalanche Node
```suggestion
# Run an Avalanche Node using the Install Script
```

2022-04-04 13:28 UTC, yulin-dong commented on docs/build/tutorials/nodes-and-staking/README.md
> +| [**Run an Avalanche Node**](set-up-node-with-installer.md) | How to install and run AvalancheGo |
```suggestion
| [**Run an Avalanche Node Using Install Script**](set-up-node-with-installer.md) | How to install and run AvalancheGo |
```

2022-04-04 13:28 UTC, yulin-dong commented on docs/build/tutorials/nodes-and-staking/README.md
> +| [**Run a node manually, or from source**](run-avalanche-node.md) | How to install without the installer script |
```suggestion
| [**Run an Avalanche Node Manually**](run-avalanche-node.md) | How to install without the installer script |
```

2022-04-04 13:55 UTC, yulin-dong approved these changes

2022-04-04 15:43 UTC, moreati commented
Thanks for reconsidering.